# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Email
email = "hi [at] example.com"

# Header Configuration
avatar = "img/avatar.jpg"

# favicon
favicon = "icons/favicon.ico"

# Whether to include the selected publications section in the homepage
displayPublication = false

# Whether to include the news section in the homepage
displayNews = true

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true